# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  image: node
  script:
    - npm i typescript
    - npx typedoc src --ignoreCompilerErrors --excludeExternals --excludeNotExported
  artifacts:
    paths:
      - public
  only:
    - master
