module.exports = {
    // Chat
    "message": require("./chat/message"),
    // Gui
    "topPrint": require("./gui/topPrint"),
    "topPrintAll": require("./gui/topPrintAll"),
    "centerPrint": require("./gui/centerPrint"),
    "centerPrintAll": require("./gui/centerPrintAll"),
    "bottomPrint": require("./gui/bottomPrint"),
    "bottomPrintAll": require("./gui/bottomPrintAll"),
    "prompt": require("./gui/prompt"),
    // Player
    "kick": require("./player/kick"),
    "sendAuthInfo": require("./player/sendAuthInfo"),
    "setAvatar": require("./player/setAvatar"),
    "getUserInfo": require("./player/getUserInfo"),
    "getRankInGroup": require("./player/getRankInGroup"),
    "playerOwnsAsset": require("./player/ownsAsset"),
    // Team
    "teamPacket": require("./team/createTeam"),
    // World
    "setEnvironment": require("./world/setEnvironment"),
    "loadBrk": require("./world/loadBrk"),
    "loadBricks": require("./world/loadBricks"),
    "addBrickProperties": require("./world/sendBrick"),
    "pickSpawn": require("./world/pickSpawn"),
    // Bot
    "botPacket": require("./bots/createBot"),
    // Tool
    "toolPacket": require("./tools/createTool")
}